services:
  pwn-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        LOWER_ROOTFS_ARCHIVE: ${LOWER_ROOTFS_ARCHIVE}
    ports:
      - "1234:1234"
    volumes:
      - ./share/:/host:rw
    tty: true
    privileged: false
    cap_add:
      - SYS_PTRACE
    command:
      bash -c "dropbear -jkEF"
      # && gdbserver 0.0.0.0:1234 ./ch6"
